### ISSUE TITLE
BrowserStack QA

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/track#3]
## Track
- [x] Default -  5 steps
https://rakuten-rex.github.io/track/iframe.html?id=track--default-view
- [x] 4 steps
https://rakuten-rex.github.io/track/iframe.html?id=track--four-steps-view
- [x] 3 steps
https://rakuten-rex.github.io/track/iframe.html?id=track--three-steps-view
- [x] All empty
https://rakuten-rex.github.io/track/iframe.html?id=track--with-dynamic-props
- [x] Theme
https://rakuten-rex.github.io/track/iframe.html?id=track--with-theme-react-and-css-vars

## Track item
- [x] Default
https://rakuten-rex.github.io/track/iframe.html?id=track-item--default-view
- [x] Current
https://rakuten-rex.github.io/track/iframe.html?id=track-item--current-status-view
- [x] Visited
https://rakuten-rex.github.io/track/iframe.html?id=track-item--visited-status-view

**Comment by montomos** [comment]
All cases have issues on Windows 10 ie 11 

**Track**
5Steps
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313636-b8672300-58a0-11ea-9a0d-4bef28392dcc.png)
4Steps
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313646-c157f480-58a0-11ea-9e45-95cb0cfb9902.png)
3Steps
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313659-cd43b680-58a0-11ea-86a8-98233483f848.png)
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313688-e0568680-58a0-11ea-9d54-b89467560d6f.png)

all
theme
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313675-d46ac480-58a0-11ea-937b-0344867e76a7.png)

**TrackItem**
default
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313716-f401ed00-58a0-11ea-9834-c829918ac16d.png)
current
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313722-fcf2be80-58a0-11ea-9f7c-2f9ba9d30736.png)
visited
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75313732-067c2680-58a1-11ea-9881-8e70cfaee19f.png)
