### ISSUE TITLE
Track Item automatic width

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/track#6]
## Component
- [x] Add automatic width and right padding of `0.5rem` to `TrackItem` to first item, items in between and not the last one. (current one is fixed width using percentage)
- [ ] The component should be aligned to the left, not centered (this one is related to automatic width)

**Reference**
Current version:
<img width="1277" alt="Screen Shot 2020-03-19 at 4 40 30 PM" src="https://user-images.githubusercontent.com/10554673/77044898-95451480-6a03-11ea-9b80-e5fe82a80f10.png">

New version:
<img width="1276" alt="Screen Shot 2020-03-19 at 4 40 13 PM" src="https://user-images.githubusercontent.com/10554673/77044828-76468280-6a03-11ea-87d0-ac29dafba52c.png">

## Theme
- [ ] Add right margin as theme prop

## Stories
- [ ] Move Max steps and Wrapper tag to the top as first and second knob
- [ ] Add limits to Max steps knob, 3 as min and 5 max
http://localhost:8080/?path=/story/track--with-dynamic-props

**Comment by montomos** [comment]
According to our previous conversation:

- keep the component centered 

- flex box as you explained it's OK for each item using same size, like material ui

**Comment by montomos** [comment]
> ## Component
> * [x]  Add automatic width and right padding of `0.5rem` to `TrackItem` to first item, items in between and not the last one. (current one is fixed width using percentage)
> * [ ]  The component should be aligned to the left, not centered (this one is related to automatic width)
> 
> **Reference**
> Current version:
> <img alt="Screen Shot 2020-03-19 at 4 40 30 PM" width="1277" src="https://user-images.githubusercontent.com/10554673/77044898-95451480-6a03-11ea-9b80-e5fe82a80f10.png">
> 
> New version:
> <img alt="Screen Shot 2020-03-19 at 4 40 13 PM" width="1276" src="https://user-images.githubusercontent.com/10554673/77044828-76468280-6a03-11ea-87d0-ac29dafba52c.png">
> 
> ## Theme
> * [ ]  Add right margin as theme prop
> 
> ## Stories
> * [ ]  Move Max steps and Wrapper tag to the top as first and second knob
> * [ ]  Add limits to Max steps knob, 3 as min and 5 max
>   http://localhost:8080/?path=/story/track--with-dynamic-props

**Comment by montomos** [comment]
> * he component should be aligned to the left, not centered (this one is related to automatic width)
> 
> **Reference**

According to our previous conversation:

- keep the component centered 

- flex box as you explained it's OK for each item using same size, like material ui
